baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-mgallery'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[module]
  replacements = 'github.com/myrthos/mod-mgallery -> ../..'
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.imports]]
    path = "github.com/myrthos/mod-mgallery"
    [[module.imports.mounts]]
      source = "dist/css/modules/mgallery/lightbox.scss"
      target = "static/css/lightbox.css"
    [[module.imports.mounts]]
      source = "dist/images"
      target = "static/images"
    [[module.imports.mounts]]
      source = "dist/js/jquery.js"
      target = "static/js/jquery.js"
    [[module.imports.mounts]]
      source = "dist/js/lightbox.js"
      target = "static/js/lightbox.js"
    [[module.imports.mounts]]
      source = "layouts/shortcodes/mgallery.html"
      target = "layouts/shortcodes/mgallery.html"
    [[module.imports.mounts]]
      source = "i18n"
      target = "i18n"
